/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TurmasLazyRouteImport = createFileRoute('/turmas')()

const TurmasLazyRoute = TurmasLazyRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/turmas.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/turmas': typeof TurmasLazyRoute
}
export interface FileRoutesByTo {
  '/turmas': typeof TurmasLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/turmas': typeof TurmasLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/turmas'
  fileRoutesByTo: FileRoutesByTo
  to: '/turmas'
  id: '__root__' | '/turmas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TurmasLazyRoute: typeof TurmasLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TurmasLazyRoute: TurmasLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
